version: '3.8'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - db_vol:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: mkhvdm/foodgram:latest
    restart: always
    volumes:
      - static_vol:/app_foodgram/static/
      - media_vol:/app_foodgram/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/app_foodgram/result_build/

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_vol:/var/html/static/
      - media_vol:/var/html/media/
    depends_on:
      - web

volumes:
  db_vol:
  static_vol:
  media_vol: