# Generated by Django 3.2.16 on 2022-12-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20221225_2240'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='favoriterecipes',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='UQ_favorite_user_recipe'),
        ),
        migrations.AddConstraint(
            model_name='shoplist',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='UQ_shoplist_user_recipe'),
        ),
    ]
