# Generated by Django 3.2.16 on 2022-12-27 21:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0006_auto_20221226_2329'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShopList',
            new_name='FavoriteRecipe',
        ),
        migrations.RenameModel(
            old_name='FavoriteRecipes',
            new_name='ShopRecipe',
        ),
        migrations.AlterModelOptions(
            name='favoriterecipe',
            options={'verbose_name': 'Избранный рецепт пользователя', 'verbose_name_plural': 'Избранные рецепты пользователя'},
        ),
        migrations.AlterModelOptions(
            name='shoprecipe',
            options={'verbose_name': 'Рецепт для списка покупок пользователя', 'verbose_name_plural': 'Рецепты для списка покупок пользователя'},
        ),
        migrations.RemoveConstraint(
            model_name='favoriterecipe',
            name='UQ_shoplist_user_recipe',
        ),
        migrations.RemoveConstraint(
            model_name='shoprecipe',
            name='UQ_favorite_user_recipe',
        ),
        migrations.AddConstraint(
            model_name='favoriterecipe',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='UQ_favorite_user_recipe'),
        ),
        migrations.AddConstraint(
            model_name='shoprecipe',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='UQ_shoplist_user_recipe'),
        ),
    ]
